fix(aliasrc): use color=auto for ls
Using color=always can create some unexpected issues
when piping the result of ls to other commands.

Like for example using pipe-rename causes the following error
with color=always.

```
The following input files do not exist:
file
file2
dir/more

Error: Nonexistent input files. Aborting.
```

https://github.com/marcusbuffett/pipe-rename