feat(mbsync): keep local archive of trash and spam
* add syncemail script that runs rsync to copy everything in Trash/Spam
  to TrashArchive and exit script if rsync fails. This way everything is
  copied to TrashArchive before mbsync deletes anything and mbsync won't
  run if rsync fails, no data should be lost.

* mbsyncrc make sure emails are moved into correct folders if they are
  moved in Far side

* fix: mbsyncrc ignore TrashArchive so mbsync doesn't end with this
  error:
  ```
    Opening far side box TrashArchive...
    Opening near side box TrashArchive...
    Error: channel fastmail: far side box TrashArchive cannot be opened.
  ```

  Which causes the systemd.service to exit as if the script failed,
  causing error logs like this:
  ```
    systemd[1305]: mbsync.service: Main process exited, code=exited, status=1/FAILURE
    systemd[1305]: mbsync.service: Failed with result 'exit-code'.
    systemd[1305]: Failed to start Mailbox synchronization service.
  ```
* add mbsync alias with the config